export const ACTIONS = {
  JOIN: 'join',
  JOINED: 'joined',
  DISCONNECTED: 'disconnected',
  ROOM_STATE: 'room-state',
  FILE_DELTA: 'file-delta',
  FILE_CONTENT: 'file-content',
  FILE_CREATE: 'file-create',
  FILE_DELETE: 'file-delete',
  FILE_RENAME: 'file-rename',
  FILE_UPDATE: 'file-update',
  WORKSPACE_SYNC: 'workspace-sync',
  WORKSPACE_REPLACE: 'workspace-replace',
  ACTIVE_FILE_CHANGE: 'active-file-change',
  CURSOR_POSITION: 'cursor-position',
  CHAT_MESSAGE: 'chat-message',
  CODE_OUTPUT: 'code-output',
  KICK_USER: 'kick-user',
  KICKED_FROM_ROOM: 'kicked-from-room',
  TRANSFER_HOST: 'transfer-host',
  HOST_TRANSFERRED: 'host-transferred',
  DELETE_ROOM: 'delete-room',
  ROOM_DELETED: 'room-deleted',
  UPDATE_ROOM_PERMISSIONS: 'update-room-permissions',
  ROOM_PERMISSIONS_UPDATED: 'room-permissions-updated',
  LEAVE_ROOM: 'leave-room',
  SYNC_CODE: 'sync-code',
  CODE_CHANGE: 'code-change',
} as const;

export type ActionType = typeof ACTIONS[keyof typeof ACTIONS];
